config/routes.rb
Rails.application.routes.draw do
  root to: "rides#index"

  resources :rides
  post 'join_ride/:ride' => 'rides#join_ride', as: :join_ride

  devise_for :users, controllers: { registrations: 'registrations' }
  get 'users/:id' => 'users#show', as: :view_profile
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ride.rb
class Ride < ApplicationRecord
  belongs_to :user

  has_and_belongs_to_many :users

  def available_seats
    self.seats - self.users.count
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :rides

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :drivers_license, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :drivers_license, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  before_action :set_ride, only: [:show, :edit, :update, :destroy]

  # GET /rides
  # GET /rides.json
  def index
    @rides = Ride.all
  end

  # GET /rides/1
  # GET /rides/1.json
  def show
  end

  # GET /rides/new
  def new
    @user = current_user
    unless @user.drivers_license.present?
      redirect_to rides_path, notice: 'You need a drivers license to create a ride!'
    end
    @ride = Ride.new user_id: @user.id
  end

  # GET /rides/1/edit
  def edit
    @user = @ride.user
  end

  # POST /rides
  # POST /rides.json
  def create
    @ride = Ride.new(ride_params)

    respond_to do |format|
      if @ride.save
        format.html { redirect_to @ride, notice: 'Ride was successfully created.' }
        format.json { render :show, status: :created, location: @ride }
      else
        format.html { render :new }
        format.json { render json: @ride.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rides/1
  # PATCH/PUT /rides/1.json
  def update
    respond_to do |format|
      if @ride.update(ride_params)
        format.html { redirect_to @ride, notice: 'Ride was successfully updated.' }
        format.json { render :show, status: :ok, location: @ride }
      else
        format.html { render :edit }
        format.json { render json: @ride.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rides/1
  # DELETE /rides/1.json
  def destroy
    @ride.destroy
    respond_to do |format|
      format.html { redirect_to rides_url, notice: 'Ride was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def join_ride
    @ride = Ride.find(params[:ride])

    if @ride.available_seats > 0
      @ride.users << current_user
    else
      redirect_to rides_path, notice: 'This ride is already full'
    end

    redirect_to @ride, notice: 'You have successfully joined this ride'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ride
      @ride = Ride.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ride_params
      params.require(:ride).permit(:user_id, :seats, :destination, :pickup, :departure, :arrival)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navigation.html.erb
<h1>UniShare</h1>
<% if user_signed_in? %>
  <%= link_to "View Profile", view_profile_path(current_user) %> |
  <%= link_to "Sign Out", destroy_user_session_path, method: 'delete' %>
<% else %>
  <%= link_to "Sign Up", new_user_registration_path %> |
  <%= link_to "Sign In", new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Unishare</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>

app/views/rides/_form.html.erb
<%= form_with(model: ride, local: true) do |form| %>
  <% if ride.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ride.errors.count, "error") %> prohibited this ride from being saved:</h2>

      <ul>
      <% ride.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <strong>Driver:</strong>
    <%= @user.name %>
  </div>
  <br/>

  <div class="field">
    <%= form.label :seats %>
    <%= form.number_field :seats, id: :ride_seats %>
  </div>

  <div class="field">
    <%= form.label :destination %>
    <%= form.text_field :destination, id: :ride_destination %>
  </div>

  <div class="field">
    <%= form.label :pickup %>
    <%= form.text_field :pickup, id: :ride_pickup %>
  </div>

  <div class="field">
    <%= form.label :departure %>
    <%= form.datetime_select :departure, id: :ride_departure %>
  </div>

  <div class="field">
    <%= form.label :arrival %>
    <%= form.datetime_select :arrival, id: :ride_arrival %>
  </div>

  <div class="field" id="ride-user-id">
    <%= form.label :user %>
    <%= form.number_field :user_id, id: :ride_user %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rides/edit.html.erb
<h2>Editing Ride</h2>

<%= render 'form', ride: @ride %>

<%= link_to 'Show', @ride %> |
<%= link_to 'Back', rides_path %>

app/views/rides/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Rides</h2>

<table>
  <thead>
    <tr>
      <th>Driver</th>
      <th>Available Seats</th>
      <th>Destination</th>
      <th>Pickup</th>
      <th>Departure</th>
      <th>Arrival</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rides.each do |ride| %>
      <tr>
        <td><%= ride.user.name %></td>
        <td><%= ride.available_seats > 0 ? ride.available_seats : "FULL" %></td>
        <td><%= ride.destination %></td>
        <td><%= ride.pickup %></td>
        <td><%= ride.departure %></td>
        <td><%= ride.arrival %></td>
        <td><%= link_to 'View Ride', ride %></td>
        <% if user_signed_in? and current_user != ride.user and !ride.users.include?(current_user) and ride.available_seats > 0 %>
          <td><%= link_to 'Join Ride', join_ride_path(ride), method: :post %></td>
        <% end %>
        <% if current_user == ride.user %>
          <td><%= link_to 'Edit', edit_ride_path(ride) %></td>
          <td><%= link_to 'Destroy', ride, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? and current_user.drivers_license.present? %>
  <%= link_to 'New Ride', new_ride_path %>
<% end %>

app/views/rides/new.html.erb
<h2>New Ride</h2>

<%= render 'form', ride: @ride %>

<%= link_to 'Back', rides_path %>

app/views/rides/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Driver:</strong>
  <%= @ride.user.name %>
</p>

<p>
  <strong>Seats Available:</strong>
  <%= @ride.available_seats > 0 ? @ride.available_seats : "FULL" %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @ride.destination %>
</p>

<p>
  <strong>Pickup:</strong>
  <%= @ride.pickup %>
</p>

<p>
  <strong>Departure:</strong>
  <%= @ride.departure %>
</p>

<p>
  <strong>Arrival:</strong>
  <%= @ride.arrival %>
</p>
<br />

<h3>Riders</h3>
<table>
  <thead>
  <tr>
    <th>Rider</th>
    <th>Email</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @ride.users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
    </tr>
  <% end %>
  </tbody>
</table>


<%= link_to 'Edit', edit_ride_path(@ride) %> |
<%= link_to 'Back', rides_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit Profile', edit_user_registration_path %>
<br />

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<% if @user.drivers_license.present? %>
  <p>
    <strong>Drivers License:</strong>
    <%= @user.drivers_license %>
  </p>
<% end %>
<br />

<% if @user.rides.count > 0 %>
  <h3>My Rides</h3>
  <table>
    <thead>
    <tr>
      <th>Driver</th>
      <th>Available Seats</th>
      <th>Destination</th>
      <th>Pickup</th>
      <th>Departure</th>
      <th>Arrival</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @user.rides.each do |ride| %>
      <tr>
        <td><%= ride.user.name %></td>
        <td><%= ride.available_seats > 0 ? ride.available_seats : "FULL" %></td>
        <td><%= ride.destination %></td>
        <td><%= ride.pickup %></td>
        <td><%= ride.departure %></td>
        <td><%= ride.arrival %></td>
        <td><%= link_to 'View Ride', ride %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

<%= link_to 'Back to Rides', rides_path %>